# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
cities_df = pd.read_csv("../WeatherPy/cities.csv", index_col=[0])
cities_df

,City,Max Temp,Lat,Lng,Humidity,Cloudiness,Wind Speed,Country,Date
0,Albany,81.00,42.60,-73.97,63,77,1.01,US,1594833642
1,Bredasdorp,50.00,-34.53,20.04,71,1,6.93,ZA,1594833642
2,Yulara,39.20,-25.24,130.99,44,0,4.70,AU,1594833642
3,Jalu,95.68,29.03,21.55,17,0,8.95,LY,1594833607
4,Sechura,71.01,-5.56,-80.82,64,84,7.83,PE,1594833642
...,...,...,...,...,...,...,...,...,...
534,Viranşehir,92.50,37.24,39.76,13,6,8.66,TR,1594833753
535,Puerto Escondido,82.40,15.85,-97.07,74,75,5.82,MX,1594833754
536,Rome,82.00,43.21,-75.46,57,1,4.70,US,1594833724
537,Imbituba,60.80,-28.24,-48.67,59,1,6.93,BR,1594833754
538,Toccoa,91.99,34.58,-83.33,52,75,3.36,US,1594833754

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# Store latitude and longitude in locations
locations = cities_df[["Lat", "Lng"]]

# Fill NaN values and convert to float
rating = cities_df["Humidity"]

In [5]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
refined_df = cities_df.loc[(cities_df["Max Temp"] > 70) & (cities_df["Max Temp"] < 80) 
                           & (cities_df["Wind Speed"] < 10) & (cities_df["Cloudiness"] == 0) ]
refined_df

,City,Max Temp,Lat,Lng,Humidity,Cloudiness,Wind Speed,Country,Date
333,Oktyabr'skiy,75.34,54.48,53.47,75,0,2.51,RU,1594833710
370,Marsá Maţrūḩ,78.03,31.35,27.25,67,0,7.29,EG,1594833656
382,Caravelas,79.34,-17.71,-39.25,64,0,6.44,BR,1594833651
426,Zverinogolovskoye,74.12,54.46,64.85,70,0,9.28,RU,1594833730
481,Derzhavīnsk,75.83,51.10,66.32,52,0,9.93,KZ,1594833742
526,Hanting,76.08,36.77,119.21,70,0,5.19,CN,1594833751

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [94]:
hotel_df = refined_df.copy()

In [104]:
# hotel_df["Hotel Name"] = ""

params = {
        "types": "hotel",
        "keyword": "hotel",
        "radius": 5000,
        "key": g_key 
}


for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    response = requests.get(base_url, params=params).json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = response['results'][0]['name']
        hotel_df.loc[index, "Hotel Lat"] = response['results'][0]['geometry']['location']['lat']
        hotel_df.loc[index, "Hotel Lng"] = response['results'][0]['geometry']['location']['lng']

    except IndexError:
        print(f"Hotel in city {row['City']} not found. skipping..")
        pass

hotel_df = hotel_df.dropna()
hotel_df

Hotel in city Zverinogolovskoye not found. skipping..

,City,Max Temp,Lat,Lng,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Lat,Hotel Lng
333,Oktyabr'skiy,75.34,54.48,53.47,75,0,2.51,RU,1594833710,Hotel Devon,54.481347,53.466940
370,Marsá Maţrūḩ,78.03,31.35,27.25,67,0,7.29,EG,1594833656,Beau Site,31.362287,27.220995
382,Caravelas,79.34,-17.71,-39.25,64,0,6.44,BR,1594833651,Mar Doce de Abrolhos,-17.743194,-39.240933
481,Derzhavīnsk,75.83,51.10,66.32,52,0,9.93,KZ,1594833742,Gostinitsa Galaktika,51.108062,66.325823
526,Hanting,76.08,36.77,119.21,70,0,5.19,CN,1594833751,Montriche International,36.728308,119.184156

In [105]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Hotel Lat", "Hotel Lng"]]

In [106]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))